### PR TITLE
Update RuboCop to v0.92 and use the Packaging extension

### PR DESCRIPTION
**Pull request by utkarsh2102**
Hi @mbj,

Thanks for your great work so far! ❤️ 
This PR updates the version of RuboCop to v0.90 and fixes some warnings like "no department given for MethodCallWithoutArgsParentheses" and et al.

This will also help us in the smooth maintenance in Debian ^.^

Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

### CODE REVIEW

**Review by mbj — APPROVED** [review]

**Comment by utkarsh2102** [comment]
Hey,

If possible, can this be included in the next release?
I'll be happy to rebase and remove merge conflicts, let me know 😄

**Comment by mbj** [comment]
@utkarsh2102 Feel free to rebase, I'll have a look than.

**Comment by utkarsh2102** [comment]
> Feel free to rebase, I'll have a look than.

Ready for your review! 🛐

**Comment by mbj** [comment]
@utkarsh2102 As your build did not run on CI I re-produced your commits with some changes in #165 and #166.

Closing this PR.

The CI setup is imperfect right now. It only builds commits I push to the repo, it does not build commits on PRs. I've yet to find a setup that allows both without duplicating the build.

**Comment by utkarsh2102** [comment]
Hi Markus,

> As your build did not run on CI I re-produced your commits with some changes in #165 and #166.

Thanks! \o/

> The CI setup is imperfect right now. It only builds commits I push to the repo, it does not build commits on PRs. I've yet to find a setup that allows both without duplicating the build.

Wow, that's interesting. I haven't really seen such a thing before though :)

**Pull request closed without merging**
