### PR TITLE
Support ruby 2.2

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mvz** [comment]
I'm sorry to see you stopped supporting 1.9.3. Apart from your testing tools, there is nothing in unparser that prohibits it from running on 1.9.3. You have now blocked off any downstream tools from using unparser and supporting 1.9.3 at the same time.

Would you consider dropping the minimal required Ruby version to 1.9.3 and simply mark it as 'not supported officially'?

**Comment by mbj** [comment]
@mvz Is there a good reason to support `1.9.3`?

I'm not aware of any downstream project that requires `1.9.3`. And a significant tool for unparser, mutant only does `>= 2.0` because it requires `TracePoint`. This is about to change as I think I can use `Coverage` in future.

Would you consider dropping the minimal required Ruby version to 1.9.3 and simply mark it as 'not supported officially'?

Yes. In case it passes specs.

**Comment by mvz** [comment]
@mbj reek uses unparser and aims to support 1.9.3.

Also, released versions of JRuby do not officially support 2.0 yet, so anyone using JRuby is basically using a 1.9.3 Ruby. Reek aims to support JRuby as well (although YAML output is currently broken).

I think the specs for unparser all pass on 1.9.3, it's just the indirect mutant dependency that causes the build to fail on Travis.

**Comment by mbj** [comment]
@mvz I released `0.2.2` with unofficial support for 1.9.3. I see chances to bring back 1.9.3 support for mutant, in that case I'll make it official again and also run 1.9.3 on CI.

**Pull request merged**
