### PR TITLE
[WIP] Fix build

### PR DESCRIPTION
**Pull request by mvz**
This is a test to see if changing devtools will get more of the build passing.

### CODE REVIEW

**Comment by mbj** [comment]
@mvz Thx for this effort. JFYI I'll be back from my vacation mid next week and work through the OSS backlog, including your PRs.

**Comment by mvz** [comment]
This PR will need to be updated to point back to the main devtools repository if and when https://github.com/mbj/devtools/pull/62 is merged.

**Comment by mvz** [comment]
Let me know if you would like to have stuff rebased or split out into separate pull requests.

**Comment by mbj** [comment]
@mvz I'm just back from vacation and catching up with commercial / OSS backlog. Give me a day or so. Again thx for your effort. I'll probably cherry pick the commits I like to reduce the diff and "not on master" code inventory, and comment on the others.

**Comment by mbj** [comment]
@mvz The build was fixed meanwhile. Closing this PR. In case I missed something in this PR feel free to open a separate one. Thx for your help.

**Pull request closed without merging**
