### PR TITLE
Relax version requirements on parser gem to allow using parser v2.5.0

### LINKED ISSUE #78: Relax parser requirements to work with 2.5.0.0+
parser 2.5.0.0 was released: https://github.com/whitequark/parser/blob/master/CHANGELOG.md

Is there any reason we can't relax the requirements to allow for 2.5.0 as well?

### PR DESCRIPTION
**Pull request by stanhu**
Closes #78

### CODE REVIEW

**Comment by mbj** [comment]
@stanhu There are some corpus test failures that need to be addressed.

Likely because rubyspec (which is part of the corpus) changed since the last time.

**Comment by stanhu** [comment]
I am seeing this single error:

```
(string):57:20: error: literal contains escape sequences incompatible with UTF-8^M
(string):57:     invalid_utf8 = "\xC3"^M
(string):57:     
```

Does this relate to https://github.com/whitequark/parser/issues/252?

**Comment by mbj** [comment]
@stanhu It likely falls into the conceptual limitations of unparser, adding an exception to the corpus test is likely the way to go.

**Comment by Confusion** [comment]
Ah, I overlooked this one when I asked my earlier question in #78. 

I can add the failing parts of rubyspec to the whitelist of files that are allowed to fail and then the build passes locally. That is because I can locally run it with versions of mutant and devtools that are modified to also support 2.5. Because of the circular dependency between the three, a commit with those changes won't pass CircleCI. Will you merge it anyway or do you want this to be addressed in another way?

**Comment by mbj** [comment]
@Confusion So if you where to PR the rubyspec whitelist, this commit turns green. I can merge it and release it.

Than we can update mutant to allow the same. This should work out.

**Comment by Confusion** [comment]
OK, so submitting https://github.com/mbj/unparser/pull/80 and rebasing this one on top of it should result in a pass.

**Comment by stanhu** [comment]
@Confusion Thanks! I rebased this branch and hope we can get this merged in soon!

**Comment by mbj** [comment]
@Confusion, @stanhu thx to you both.

Its not like I'm not interested in merging, but I',m to busy in more important work otherwise to do the heavy lifting.

**Comment by stanhu** [comment]
@mbj Thanks! Could you spare of a few minutes of your time to push a new release? :)

**Comment by mbj** [comment]
> @mbj Thanks! Could you spare of a few minutes of your time to push a new release? :)

`unparser-0.2.7` was just released.

OT: Where do you use unparser / mutant?

**Comment by stanhu** [comment]
Thanks!

At GitLab, we're using the [rspec-parameterized](https://github.com/tomykaira/rspec-parameterized) gem, which looks like it depends on unparser and parser.

**Comment by mbj** [comment]
@stanhu ahh I see. 

If you ever wanna try mutant (the reason unparser exists), ping me.

**Pull request merged**
