### PR TITLE
Improve empty dstr

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by dgollahon** [comment]
Isn't an empty dstr `""`? I'm curious why `%()` would be preferred over `""`, am I missing something?

**Comment by mbj** [comment]
@dgollahon 

> Isn't an empty dstr ""? 

no:

```
$ bundle exec ruby-parse -e '""'
(str "")
```

Hence, if unparser has to generate something that parses as `(dstr)` (from source that originally parsed as `dstr`) I need to emit syntax that on parsing produces a `(dstr)` again which is:

```
$ bundle exec ruby-parse -e '%()'
(dstr)
```

So unparsing `(dstr)` as `""` concrete syntax would violate unparsers round trip property. As I'd, given `%()` as parse input that produces `(dstr)` would unparse it as `""` which when parses would parse as `(str "")`.

**Comment by mbj** [comment]
And before @palkan made me aware in https://github.com/ruby-next/ruby-next/pull/61, I was not aware `(dstr)` can be produced any other way than an empty heredoc.

BTW: Its likely unparser right now emits too many heredocs (that still produce correct AST when parsed) and in some, sort string, cases I actually want to prefer `%()` over heredocs.

**Comment by mbj** [comment]
@dgollahon Feel free to try `bundle exec unparser -e '%()'` after changing the `write('%()')` I added to `write('"")` in this PR. You'll see all I said above failing the invariant the unparser CLI checks.

**Comment by dgollahon** [comment]
> And before @palkan made me aware in ruby-next/ruby-next#61, I was not aware (dstr) can be produced any other way than an empty heredoc.

Wow, that is pretty strange. I would have expected interpolation to be required for something to be a `(dstr)`. I wonder why `parser` does it that way?

**Comment by mbj** [comment]
> I wonder why `parser` does it that way?

I suspect his particular case is an artifact. Just like `""` is not a dstr until an interpolation is used ´%()` could stay an `str` till an interpolation is used.

But: Ruby has a very complex syntax, and I suspect in the end it was simpler to support general delimited input via not doing these kinds of optimizations. Its likely that the complexity budget when changing this semantics would blow something else.

I'm not convinced that this particular case, if fixed would be worth it.

**Comment by mbj** [comment]
@dgollahon Also pretty strange and suprised? This. Is. Ruby. (imagine sparta meme here).

**Comment by dgollahon** [comment]
> I'm not convinced that this particular case, if fixed would be worth it.

Yeah, it may or may not be. I find it surprising that alternate forms of quoting would be different from `""` but it could very well break more upstream code than it would help. Might be interesting to dig into some other day for my own curiosity.

> @dgollahon Also pretty strange and suprised? This. Is. Ruby. (imagine sparta meme here).

haha. In this case it seems to be arbitrary or maybe more of a `parser` choice than ruby itself... but yes, weirdness is to be expected in Rubyland. 😆

**Comment by mbj** [comment]
> Yeah, it may or may not be. I find it surprising that alternate forms of quoting would be different from `""` but it could very well break more upstream code than it would help. Might be interesting to dig into some other day for my own curiosity.

So I'd give it a 90% chance that the parser author (I'm not tagging her intentionally as AFAIK she is distancing herself from Ruby / parser), had a good reason to not emit `str` here.

I still think the current maintainers of `parser` would be interested to answer your question. My stance is: Unparser has a specific guarantee on the generated concrete syntax, and as long parser produces `dstr` here I better emit source that parses to `dstr`.

I'd be happy to remove these special handlings from unparsers code, but I have to support current environment not hypothetical better ones ;)

**Comment by dgollahon** [comment]
Yeah, there may be a reason for it. I suspect it is just awkward to special case consistently, but not sure!

Yeah, given the situation I support this change 👍

Definitely looked funny to me so I wanted to learn more. Thanks for the explanation.

**Comment by mbj** [comment]
> Thanks for the explanation.

Thanks for giving me the opportunity to do so.

**Pull request merged**
